/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: polyman (https://sketchfab.com/Polyman_3D)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/apple-iphone-15-pro-max-black-df17520841214c1792fb8a44c6783ee7
Title: Apple iPhone 15 Pro Max Black
*/

import { useGLTF, useTexture } from "@react-three/drei";
import type React from "react";
import { useEffect } from "react";
import type { Mesh } from "three";

import type { Model } from "../constants";

type IPhoneProps = {
  item: Model;
  scale?: number;
  size?: "small" | "large";
};

type GLTFResult = {
  nodes: Record<string, unknown>;
  materials: Record<string, import("three").Material>;
};

const IPhone: React.FC<IPhoneProps> = (props) => {
  const { nodes, materials } = useGLTF(
    "/models/scene.glb"
  ) as unknown as GLTFResult;

  const texture = useTexture(props.item.img);

  useEffect(() => {
    for (const [key, material] of Object.entries(materials)) {
      if (
        key !== "dxCVrUCvYhjVxqy" &&
        key !== "hUlRcbieVuIiOXG" &&
        key !== "PaletteMaterial001" &&
        key !== "PaletteMaterial002"
      ) {
        const m = material as import("three").MeshStandardMaterial;
        m.map = texture;
        m.needsUpdate = true;
      }
    }
  }, [materials, texture]);

  return (
    <group>
      <mesh
        castShadow
        geometry={(nodes.ttmRoLdJipiIOmf as Mesh).geometry}
        material={materials.hUlRcbieVuIiOXG}
        receiveShadow
        scale={props.scale || 1}
      >
        <meshStandardMaterial color={props.item.color[0]} />
      </mesh>
      <mesh
        castShadow
        geometry={(nodes.DjsDkGiopeiEJZK as Mesh).geometry}
        material={materials.PaletteMaterial001}
        receiveShadow
        scale={props.scale || 1}
      >
        <meshStandardMaterial color={props.item.color[1]} />
      </mesh>
      <mesh
        castShadow
        geometry={(nodes.buRWvyqhBBgcJFo as Mesh).geometry}
        material={materials.PaletteMaterial002}
        receiveShadow
        scale={props.scale || 1}
      >
        <meshStandardMaterial color={props.item.color[2]} />
      </mesh>
      <mesh
        castShadow
        geometry={(nodes.MrMmlCAsAxJpYqQ_0 as Mesh).geometry}
        material={materials.dxCVrUCvYhjVxqy}
        receiveShadow
        scale={props.scale || 1}
      />
      <mesh
        castShadow
        geometry={(nodes.wqbHSzWaUxBCwxY_0 as Mesh).geometry}
        material={materials.MHFGNLrDQbTNima}
        receiveShadow
        scale={props.scale || 1}
      />
      <mesh
        castShadow
        geometry={(nodes.QvGDcbDApaGssma as Mesh).geometry}
        material={materials.kUhjpatHUvkBwfM}
        receiveShadow
        scale={0.01}
      />
      <mesh
        castShadow
        geometry={(nodes.vFwJFNASGvEHWhs as Mesh).geometry}
        material={materials.RJoymvEsaIItifI}
        receiveShadow
        scale={0.01}
      />
      <mesh
        castShadow
        geometry={(nodes.evAxFwhaQUwXuua as Mesh).geometry}
        material={materials.KSIxMqttXxxmOYl}
        receiveShadow
        scale={0.01}
      />
      <mesh
        castShadow
        geometry={(nodes.USxQiqZgxHbRvqB as Mesh).geometry}
        material={materials.mcPrzcBUcdqUybC}
        receiveShadow
        scale={0.01}
      />
      <mesh
        castShadow
        geometry={(nodes.TvgBVmqNmSrFVfW as Mesh).geometry}
        material={materials.pIhYLPqiSQOZTjn}
        receiveShadow
        scale={0.01}
      />
      <mesh
        castShadow
        geometry={(nodes.GuYJryuYunhpphO as Mesh).geometry}
        material={materials.eShKpuMNVJTRrgg}
        receiveShadow
        scale={0.01}
      />
      <mesh
        castShadow
        geometry={(nodes.pvdHknDTGDzVpwc as Mesh).geometry}
        material={materials.xdyiJLYTYRfJffH}
        receiveShadow
        scale={0.01}
      />
      <mesh
        castShadow
        geometry={(nodes.CfghdUoyzvwzIum as Mesh).geometry}
        material={materials.jpGaQNgTtEGkTfo}
        receiveShadow
        scale={0.01}
      />
      <mesh
        castShadow
        geometry={(nodes.DjdhycfQYjKMDyn as Mesh).geometry}
        material={materials.ujsvqBWRMnqdwPx}
        receiveShadow
        scale={0.01}
      />
      <mesh
        castShadow
        geometry={(nodes.usFLmqcyrnltBUr as Mesh).geometry}
        material={materials.sxNzrmuTqVeaXdg}
        receiveShadow
        scale={0.01}
      />
      <mesh
        castShadow
        geometry={(nodes.xXDHkMplTIDAXLN as Mesh).geometry}
        material={materials.pIJKfZsazmcpEiU}
        receiveShadow
        scale={0.01}
      >
        <meshStandardMaterial map={texture} roughness={1} />
      </mesh>
      <mesh
        castShadow
        geometry={(nodes.vELORlCJixqPHsZ as Mesh).geometry}
        material={materials.zFdeDaGNRwzccye}
        receiveShadow
        scale={0.01}
      />
      <mesh
        castShadow
        geometry={(nodes.EbQGKrWAqhBHiMv as Mesh).geometry}
        material={materials.TBLSREBUyLMVtJa}
        receiveShadow
        scale={0.01}
      />
      <mesh
        castShadow
        geometry={(nodes.EddVrWkqZTlvmci as Mesh).geometry}
        material={materials.xNrofRCqOXXHVZt}
        receiveShadow
        scale={0.01}
      />
      <mesh
        castShadow
        geometry={(nodes.KSWlaxBcnPDpFCs as Mesh).geometry}
        material={materials.yQQySPTfbEJufve}
        receiveShadow
        scale={0.01}
      />
      <mesh
        castShadow
        geometry={(nodes.TakBsdEjEytCAMK as Mesh).geometry}
        material={materials.PaletteMaterial003}
        receiveShadow
        scale={0.01}
      />
      <mesh
        castShadow
        geometry={(nodes.IykfmVvLplTsTEW as Mesh).geometry}
        material={materials.PaletteMaterial004}
        receiveShadow
        scale={0.01}
      />
      <mesh
        castShadow
        geometry={(nodes.wLfSXtbwRlBrwof as Mesh).geometry}
        material={materials.oZRkkORNzkufnGD}
        receiveShadow
        scale={0.01}
      />
      <mesh
        castShadow
        geometry={(nodes.WJwwVjsahIXbJpU as Mesh).geometry}
        material={materials.yhcAXNGcJWCqtIS}
        receiveShadow
        scale={0.01}
      />
      <mesh
        castShadow
        geometry={(nodes.YfrJNXgMvGOAfzz as Mesh).geometry}
        material={materials.bCgzXjHOanGdTFV}
        receiveShadow
        scale={0.01}
      />
      <mesh
        castShadow
        geometry={(nodes.DCLCbjzqejuvsqH as Mesh).geometry}
        material={materials.vhaEJjZoqGtyLdo}
        receiveShadow
        scale={0.01}
      />
      <mesh
        castShadow
        geometry={(nodes.CdalkzDVnwgdEhS as Mesh).geometry}
        material={materials.jlzuBkUzuJqgiAK}
        receiveShadow
        scale={0.01}
      />
      <mesh
        castShadow
        geometry={(nodes.NtjcIgolNGgYlCg as Mesh).geometry}
        material={materials.PpwUTnTFZJXxCoE}
        receiveShadow
        scale={0.01}
      />
      <mesh
        castShadow
        geometry={(nodes.pXBNoLiaMwsDHRF as Mesh).geometry}
        material={materials.yiDkEwDSyEhavuP}
        receiveShadow
        scale={0.01}
      />
      <mesh
        castShadow
        geometry={(nodes.IkoiNqATMVoZFKD as Mesh).geometry}
        material={materials.hiVunnLeAHkwGEo}
        receiveShadow
        scale={0.01}
      />
      <mesh
        castShadow
        geometry={(nodes.rqgRAGHOwnuBypi as Mesh).geometry}
        material={materials.HGhEhpqSBZRnjHC}
        receiveShadow
        scale={0.01}
      />
    </group>
  );
};

export default IPhone;

useGLTF.preload("/models/scene.glb");
